### ISSUE TITLE
关于yolo_calibration.cache的问题

### ISSUE THREAD

**Issue by 205418367** [mynotwo/yolov3_tensorRT_int8_calibration#2]
生成yolo_calibration.cache的batch size是1，会不会影响精度？

**Comment by 205418367** [comment]
问题二：yolov3.onnx与yolo_calibration.cache这两个文件加载时间长，然后生成yolo_in8.trt文件。请问，前两个文件只需要加载一次？第二次只需要加载生成的trf文件即可？

**Comment by mynotwo** [comment]
1.batch size并不影响calibration的精度，我把batch size设置为1是因为不这样貌似会出现core dumped....
2.前两个文件确实只需要加载一次，生成对应的engine之后加载trt即可

**Comment by 205418367** [comment]
我的tensort5.1.5在1080ti上运行，出现了下面的问题：
[TensorRT] ERROR: ../builder/cudnnBuilder2.cpp (1791) - Misc Error in createRegionScalesFromTensorScales: -1 (Could not find scales for tensor softmax0 copy.)
[TensorRT] ERROR: ../builder/cudnnBuilder2.cpp (1791) - Misc Error in createRegionScalesFromTensorScales: -1 (Could not find scales for tensor softmax0 copy.)

你知道是什么原因吗？

**Comment by 205418367** [comment]
是不是softmax层不能量化？
